name: "setup-cf"
author: "Christopher Banck"
description: "Setup Cloud Foundry CLI environment."
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  api:
    description: "Url of the cloud controller api"
    required: true
  audience:
    description: "github id_token audience"
    required: false
  client_id:
    description: "client id"
    required: false
  client_secret:
    description: "client secret"
    required: false
  grant_type:
    description: "grant type for requesting token"
    required: true
    default: "password"
  jwt:
    description: "jwt for usage with `client_credentials` or `jwt-bearer`."
    required: false
  org:
    description: "org"
    required: false
  origin:
    description: "origin"
    required: false
  username:
    description: "username"
    required: false
  password:
    description: "password"
    required: false
  skip_ssl_validation:
    description: "skip_ssl_validation"
    required: false
    default: "false"
  space:
    description: "space"
    required: false
  version:
    description: "cf cli version"
    required: true
    default: "8.12.0"
runs:
  using: "node20"
  main: "dist/index.js"
